config/routes.rb
Rails.application.routes.draw do

  match ':controller(/:action(/:id))', via: [:get, :post]
  match 'auth/:provider/callback', to: 'social#new', via: [:get, :post]
  match 'auth/failure', to: 'home#index', via: [:get, :post]
  match 'signout', to: 'social#destroy', as: 'signout', via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base


  def self.from_omniauth(auth)
    case auth.provider
      when 'facebook' then
        self.omniauth_facebook(auth)
      when 'google_oauth2' then
        omniauth_google(auth)
      else
        nil
    end
  end

  private
  def self.omniauth_facebook(auth)
    # 認証時のトークンを使ってGraphAPIで日本語情報を取得
    facebook = Koala::Facebook::API.new(auth.credentials.token)
    result = facebook.get_object('/me', { locale: 'ja_JP' })

    user = User.new
    user.provider = auth.provider
    user.uid = result['id']
    user.name = result['name']
    user.email = result['email']
    return user
  end

  private
  def self.omniauth_google(auth)
    user = User.new
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/social_controller.rb
class SocialController < ApplicationController
  def new
    logger.debug(request.env['omniauth.auth'])
    @user = User.from_omniauth(request.env['omniauth.auth'])
    unless @user
      redirect_to action: 'oauth_failure'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:provider] = @user.provider
      session[:uid] = @user.uid
      session[:name] = @user.name
      session[:email] = @user.email
      redirect_to '/home/index'
    else
      render action: 'new'
    end
  end

  def destroy
    reset_session
    redirect_to '/home/index', :notice => 'サインアウトしました'
  end

  def oauth_failure
    redirect_to '/home/index', :notice => 'サインイン処理が中断されました'
  end

  private
  def user_params
    params.require(:user).permit(:provider, :uid, :name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/social_helper.rb
module SocialHelper
end

app/views/home/index.html.erb
<div id="user-widget">
  <% if session[:uid] %>
    ようこそ <%= session[:name] %><br>
    <%= link_to 'Sign out', signout_path, id: 'sign_out' %>
  <% else %>
    <%= link_to 'Sign in with FaceBook', '/auth/facebook', id:'sign_in' %><br>
    <%= link_to 'Sign in with Google', '/auth/google_oauth2', id:'sign_in' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TOauthApl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/social/new.html.erb
<div id="user-widget">
  <%= form_for(@user, url: url_for(action: :create)) do |f| %>
    <div class="field">
      <%= f.label :provider %><br>
      <%= f.text_field :provider %>
    </div>
    <div class="field">
      <%= f.label :uid %><br>
      <%= f.text_field :uid %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
       <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>